CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name varchar NOT NULL,
   email varchar NOT NULL,
   password varchar NOT NULL,
   access varchar NOT NULL,
   CONSTRAINT pk_user_id PRIMARY KEY (id)
);

