#o perfil prod está configurado para usar banco h2, as migrations devem ser na sintaxe de h2

spring:
  datasource:
    url: jdbc:h2:mem:vendas_track_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.show_sql: true
      hibernate:
        ddl-auto: none
        format_sql: false
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: none
    hibernate:
      ddl-auto: create

  flyway:
    locations: classpath:db/migration/h2
    enabled: true
    baseline-on-migrate: true

  h2:
    console:
      enabled: true
      path: /h2
security:
  config:
    key: qwe123
    expiration: 3

logging:
  level:
    org:
      springframework: DEBUG
      flywaydb: DEBUG


