spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sysagua_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwe123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      format-sql: false
      enable_lazy_load_no_trans: false

  flyway:
    locations: classpath:db/migration/postgres
    baseline-on-migrate: true
    enabled: true